
version: "3.8"
services:
  react-app:
    image: shhubh7/react-movie-app:latest
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    image: shhubh7/movie-api-server:latest
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local


# version: "3.8"
# services:
#   react-app:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     stdin_open: true
#     ports: 
#       - "3000:3000"
#     networks:
#       - mern-app

#   api-server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     networks:
#       - mern-app
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:3.6.19-xenial
#     ports:
#       - "27017:27017"
#     networks:
#       - mern-app
#     volumes:
#       - mongo-data:/data/db

# networks:
#   mern-app:
#     driver: bridge

# volumes:
#   mongo-data:
#     driver: local

